[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pilot"
version = "1.0.0"
description = "CLI for RPA tasks"
readme = "README.md"
requires-python = ">=3.7"

[project.scripts]
pilot = "pilot.cli.main:program.run"

[tool.setuptools.packages.find]
where = ["."]
